import { MigrationInterface, QueryRunner } from "typeorm";

export class MigrationName1751158934471 implements MigrationInterface {
    name = 'MigrationName1751158934471'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "sprint" ("id" SERIAL NOT NULL, "project_id" integer NOT NULL, "sprint_name" character varying NOT NULL, "start_date" TIMESTAMP NOT NULL, "end_date" TIMESTAMP NOT NULL, "location" character varying NOT NULL DEFAULT '', "projectProjectId" integer, CONSTRAINT "PK_f371c7b5c4bc62fb2ba2bdb9f61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project" ("project_id" SERIAL NOT NULL, "project_description" character varying, "project_name" character varying NOT NULL, "projectCreatorId" integer, CONSTRAINT "PK_1a480c5734c5aacb9cef7b1499d" PRIMARY KEY ("project_id"))`);
        await queryRunner.query(`CREATE TABLE "project_member" ("id" SERIAL NOT NULL, "role" character varying NOT NULL, "user_id" integer, "project_id" integer, CONSTRAINT "PK_64dba8e9dcf96ce383cfd19d6fb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "User" ("id" SERIAL NOT NULL, "displayname" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, CONSTRAINT "PK_9862f679340fb2388436a5ab3e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "discussion" ("commentid" SERIAL NOT NULL, "message" character varying NOT NULL, "createdat" TIMESTAMP NOT NULL, "workitemId" integer, "creatorid" integer, CONSTRAINT "PK_5934d259c28b4cfe1ad0522df30" PRIMARY KEY ("commentid"))`);
        await queryRunner.query(`CREATE TABLE "tags" ("id" SERIAL NOT NULL, "tagname" character varying NOT NULL, CONSTRAINT "UQ_5620ac7fe1862be3a036bbfab38" UNIQUE ("tagname"), CONSTRAINT "PK_e7dc17249a1148a1970748eda99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."planning_risk_enum" AS ENUM('High', 'Medium', 'Low')`);
        await queryRunner.query(`CREATE TABLE "planning" ("planning_id" SERIAL NOT NULL, "priority" integer NOT NULL, "story_point" integer, "risk" "public"."planning_risk_enum", "effort" integer, "business_value" integer, "time_criticality" integer, "start_date" TIMESTAMP, "target_date" TIMESTAMP, CONSTRAINT "PK_4649f23f073cf8df2ab7b877fb0" PRIMARY KEY ("planning_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."workitem_type_enum" AS ENUM('Epic', 'Feature', 'Bug', 'Task', 'UserStory')`);
        await queryRunner.query(`CREATE TYPE "public"."workitem_state_enum" AS ENUM('New', 'Active', 'Resolved', 'Closed', 'Removed')`);
        await queryRunner.query(`CREATE TABLE "workitem" ("id" SERIAL NOT NULL, "type" "public"."workitem_type_enum" NOT NULL, "title" character varying NOT NULL, "state" "public"."workitem_state_enum" NOT NULL, "description" character varying NOT NULL, "assigned_to" integer, "activity_date" TIMESTAMP NOT NULL, "area_path" character varying NOT NULL, "iteration" character varying, "updated_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL, "completed_at" TIMESTAMP NOT NULL, "classification" character varying NOT NULL, "sprint_id" integer, "acceptance_criteria" character varying, "inheritance_type" character varying NOT NULL, "created_by" integer, "project_id" integer, "parentId" integer, "planning_id" integer, "sprintId" integer, CONSTRAINT "REL_91b83126018679cac7433168cf" UNIQUE ("planning_id"), CONSTRAINT "PK_ace2c8f08093dedabeda37b71d8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_95ec63252523517b0b499e2a3f" ON "workitem" ("inheritance_type") `);
        await queryRunner.query(`CREATE TYPE "public"."Epic_type_enum" AS ENUM('Epic', 'Feature', 'Bug', 'Task', 'UserStory')`);
        await queryRunner.query(`CREATE TYPE "public"."Epic_state_enum" AS ENUM('New', 'Active', 'Resolved', 'Closed', 'Removed')`);
        await queryRunner.query(`CREATE TABLE "Epic" ("id" SERIAL NOT NULL, "type" "public"."Epic_type_enum" NOT NULL, "title" character varying NOT NULL, "state" "public"."Epic_state_enum" NOT NULL, "description" character varying NOT NULL, "assigned_to" integer, "activity_date" TIMESTAMP NOT NULL, "area_path" character varying NOT NULL, "iteration" character varying, "updated_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL, "completed_at" TIMESTAMP NOT NULL, "classification" character varying NOT NULL, "sprint_id" integer, "created_by" integer, "project_id" integer, "parentId" integer, "planning_id" integer, "sprintId" integer, CONSTRAINT "REL_2a1adf93f3dbc64246c130a308" UNIQUE ("planning_id"), CONSTRAINT "PK_ec04c79ff2d04c2efda15442dd6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."feature_type_enum" AS ENUM('Epic', 'Feature', 'Bug', 'Task', 'UserStory')`);
        await queryRunner.query(`CREATE TYPE "public"."feature_state_enum" AS ENUM('New', 'Active', 'Resolved', 'Closed', 'Removed')`);
        await queryRunner.query(`CREATE TABLE "feature" ("id" SERIAL NOT NULL, "type" "public"."feature_type_enum" NOT NULL, "title" character varying NOT NULL, "state" "public"."feature_state_enum" NOT NULL, "description" character varying NOT NULL, "assigned_to" integer, "activity_date" TIMESTAMP NOT NULL, "area_path" character varying NOT NULL, "iteration" character varying, "updated_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL, "completed_at" TIMESTAMP NOT NULL, "classification" character varying NOT NULL, "sprint_id" integer, "created_by" integer, "project_id" integer, "parentId" integer, "planning_id" integer, "sprintId" integer, CONSTRAINT "REL_313047df0954669919a5b855dd" UNIQUE ("planning_id"), CONSTRAINT "PK_03930932f909ca4be8e33d16a2d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_story_type_enum" AS ENUM('Epic', 'Feature', 'Bug', 'Task', 'UserStory')`);
        await queryRunner.query(`CREATE TYPE "public"."user_story_state_enum" AS ENUM('New', 'Active', 'Resolved', 'Closed', 'Removed')`);
        await queryRunner.query(`CREATE TABLE "user_story" ("id" SERIAL NOT NULL, "type" "public"."user_story_type_enum" NOT NULL, "title" character varying NOT NULL, "state" "public"."user_story_state_enum" NOT NULL, "description" character varying NOT NULL, "assigned_to" integer, "activity_date" TIMESTAMP NOT NULL, "area_path" character varying NOT NULL, "iteration" character varying, "updated_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL, "completed_at" TIMESTAMP NOT NULL, "classification" character varying NOT NULL, "sprint_id" integer, "acceptance_criteria" character varying, "created_by" integer, "project_id" integer, "parentId" integer, "planning_id" integer, "sprintId" integer, CONSTRAINT "REL_f4a31af30f6472a7f0ac7a72df" UNIQUE ("planning_id"), CONSTRAINT "PK_cd6f5a48fae7109fbc55f19720e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "workitem_tags_tags" ("workitemId" integer NOT NULL, "tagsId" integer NOT NULL, CONSTRAINT "PK_3d1a376d35bdf1f195eb703f11c" PRIMARY KEY ("workitemId", "tagsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bfae51d139fe3ffd6d3936eb26" ON "workitem_tags_tags" ("workitemId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d0171023239e6acba6c3aa4a8e" ON "workitem_tags_tags" ("tagsId") `);
        await queryRunner.query(`CREATE TABLE "epic_tags_tags" ("epicId" integer NOT NULL, "tagsId" integer NOT NULL, CONSTRAINT "PK_e46a551290b2cbcca10f6f23719" PRIMARY KEY ("epicId", "tagsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2c76d2381e0d70dd020c58fec8" ON "epic_tags_tags" ("epicId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2aa188f4d155734448d318f3ab" ON "epic_tags_tags" ("tagsId") `);
        await queryRunner.query(`CREATE TABLE "feature_tags_tags" ("featureId" integer NOT NULL, "tagsId" integer NOT NULL, CONSTRAINT "PK_431d8865f0d607e4c089e1ee6aa" PRIMARY KEY ("featureId", "tagsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c11c3d7ebca48ade507892449d" ON "feature_tags_tags" ("featureId") `);
        await queryRunner.query(`CREATE INDEX "IDX_716bcb0af33e71263af530e1fd" ON "feature_tags_tags" ("tagsId") `);
        await queryRunner.query(`CREATE TABLE "user_story_tags_tags" ("userStoryId" integer NOT NULL, "tagsId" integer NOT NULL, CONSTRAINT "PK_a169f8dfcfd65fab5910244c0b5" PRIMARY KEY ("userStoryId", "tagsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_df9eb6d28d3088641e8992776d" ON "user_story_tags_tags" ("userStoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e94e9a75d10fdc7e34fb8deb61" ON "user_story_tags_tags" ("tagsId") `);
        await queryRunner.query(`ALTER TABLE "sprint" ADD CONSTRAINT "FK_d43446a72eb18ee4cd06a8a510d" FOREIGN KEY ("projectProjectId") REFERENCES "project"("project_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project" ADD CONSTRAINT "FK_6b512aa40369ca997e833f568ce" FOREIGN KEY ("projectCreatorId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_member" ADD CONSTRAINT "FK_c5aa3e0aec43d3459e159d21dd3" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_member" ADD CONSTRAINT "FK_aaef76230abfcdf30adb15d0be8" FOREIGN KEY ("project_id") REFERENCES "project"("project_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discussion" ADD CONSTRAINT "FK_6a5c08cba60dde8720f8e86da9d" FOREIGN KEY ("workitemId") REFERENCES "workitem"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discussion" ADD CONSTRAINT "FK_619cb0165968ce3632e71f929d8" FOREIGN KEY ("creatorid") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workitem" ADD CONSTRAINT "FK_6ac10d55b031facc4808deda253" FOREIGN KEY ("created_by") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workitem" ADD CONSTRAINT "FK_fb11a5d6971c2a341aa1f3f3943" FOREIGN KEY ("assigned_to") REFERENCES "project_member"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workitem" ADD CONSTRAINT "FK_ed18c8b38a8921df0008cc4577f" FOREIGN KEY ("project_id") REFERENCES "project"("project_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workitem" ADD CONSTRAINT "FK_82668fcf730240dc924f9b7e68c" FOREIGN KEY ("parentId") REFERENCES "workitem"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workitem" ADD CONSTRAINT "FK_91b83126018679cac7433168cfb" FOREIGN KEY ("planning_id") REFERENCES "planning"("planning_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workitem" ADD CONSTRAINT "FK_f0947da6fb5b37de0826cf7d148" FOREIGN KEY ("sprintId") REFERENCES "sprint"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Epic" ADD CONSTRAINT "FK_5c6d1d8cd86a91c25aff7b33bf1" FOREIGN KEY ("created_by") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Epic" ADD CONSTRAINT "FK_ef76326f3b3a9431f920615af7e" FOREIGN KEY ("assigned_to") REFERENCES "project_member"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Epic" ADD CONSTRAINT "FK_245575a06243d764b5dafb6a3b4" FOREIGN KEY ("project_id") REFERENCES "project"("project_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Epic" ADD CONSTRAINT "FK_a0ca985e88555e335ea702790fd" FOREIGN KEY ("parentId") REFERENCES "workitem"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Epic" ADD CONSTRAINT "FK_2a1adf93f3dbc64246c130a3085" FOREIGN KEY ("planning_id") REFERENCES "planning"("planning_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Epic" ADD CONSTRAINT "FK_e3a15ca42ced20d50f91bc1b785" FOREIGN KEY ("sprintId") REFERENCES "sprint"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feature" ADD CONSTRAINT "FK_00c4427a81e82a5ee40b1b40e97" FOREIGN KEY ("created_by") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feature" ADD CONSTRAINT "FK_dc2864acf0c06997e5dc0f47dbe" FOREIGN KEY ("assigned_to") REFERENCES "project_member"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feature" ADD CONSTRAINT "FK_0a48658f04433e8a6ccb0a57187" FOREIGN KEY ("project_id") REFERENCES "project"("project_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feature" ADD CONSTRAINT "FK_d4a28a8e70d450a412bf0cfb52a" FOREIGN KEY ("parentId") REFERENCES "workitem"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feature" ADD CONSTRAINT "FK_313047df0954669919a5b855dde" FOREIGN KEY ("planning_id") REFERENCES "planning"("planning_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feature" ADD CONSTRAINT "FK_d378ad58975a8693f95bc68c71a" FOREIGN KEY ("sprintId") REFERENCES "sprint"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_story" ADD CONSTRAINT "FK_1b66e59967f8fbf44cb692a8b9a" FOREIGN KEY ("created_by") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_story" ADD CONSTRAINT "FK_53ea109ed6a05ae6f9fdc33f794" FOREIGN KEY ("assigned_to") REFERENCES "project_member"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_story" ADD CONSTRAINT "FK_443b0bff9788f060fe1a8ba617b" FOREIGN KEY ("project_id") REFERENCES "project"("project_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_story" ADD CONSTRAINT "FK_0d12b2f67ecebc4fe0b5f7bf845" FOREIGN KEY ("parentId") REFERENCES "workitem"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_story" ADD CONSTRAINT "FK_f4a31af30f6472a7f0ac7a72df6" FOREIGN KEY ("planning_id") REFERENCES "planning"("planning_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_story" ADD CONSTRAINT "FK_c1959e3c38e148e3f471807fa81" FOREIGN KEY ("sprintId") REFERENCES "sprint"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workitem_tags_tags" ADD CONSTRAINT "FK_bfae51d139fe3ffd6d3936eb260" FOREIGN KEY ("workitemId") REFERENCES "workitem"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "workitem_tags_tags" ADD CONSTRAINT "FK_d0171023239e6acba6c3aa4a8ec" FOREIGN KEY ("tagsId") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "epic_tags_tags" ADD CONSTRAINT "FK_2c76d2381e0d70dd020c58fec86" FOREIGN KEY ("epicId") REFERENCES "Epic"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "epic_tags_tags" ADD CONSTRAINT "FK_2aa188f4d155734448d318f3abd" FOREIGN KEY ("tagsId") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feature_tags_tags" ADD CONSTRAINT "FK_c11c3d7ebca48ade507892449d2" FOREIGN KEY ("featureId") REFERENCES "feature"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "feature_tags_tags" ADD CONSTRAINT "FK_716bcb0af33e71263af530e1fdf" FOREIGN KEY ("tagsId") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_story_tags_tags" ADD CONSTRAINT "FK_df9eb6d28d3088641e8992776d0" FOREIGN KEY ("userStoryId") REFERENCES "user_story"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_story_tags_tags" ADD CONSTRAINT "FK_e94e9a75d10fdc7e34fb8deb616" FOREIGN KEY ("tagsId") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_story_tags_tags" DROP CONSTRAINT "FK_e94e9a75d10fdc7e34fb8deb616"`);
        await queryRunner.query(`ALTER TABLE "user_story_tags_tags" DROP CONSTRAINT "FK_df9eb6d28d3088641e8992776d0"`);
        await queryRunner.query(`ALTER TABLE "feature_tags_tags" DROP CONSTRAINT "FK_716bcb0af33e71263af530e1fdf"`);
        await queryRunner.query(`ALTER TABLE "feature_tags_tags" DROP CONSTRAINT "FK_c11c3d7ebca48ade507892449d2"`);
        await queryRunner.query(`ALTER TABLE "epic_tags_tags" DROP CONSTRAINT "FK_2aa188f4d155734448d318f3abd"`);
        await queryRunner.query(`ALTER TABLE "epic_tags_tags" DROP CONSTRAINT "FK_2c76d2381e0d70dd020c58fec86"`);
        await queryRunner.query(`ALTER TABLE "workitem_tags_tags" DROP CONSTRAINT "FK_d0171023239e6acba6c3aa4a8ec"`);
        await queryRunner.query(`ALTER TABLE "workitem_tags_tags" DROP CONSTRAINT "FK_bfae51d139fe3ffd6d3936eb260"`);
        await queryRunner.query(`ALTER TABLE "user_story" DROP CONSTRAINT "FK_c1959e3c38e148e3f471807fa81"`);
        await queryRunner.query(`ALTER TABLE "user_story" DROP CONSTRAINT "FK_f4a31af30f6472a7f0ac7a72df6"`);
        await queryRunner.query(`ALTER TABLE "user_story" DROP CONSTRAINT "FK_0d12b2f67ecebc4fe0b5f7bf845"`);
        await queryRunner.query(`ALTER TABLE "user_story" DROP CONSTRAINT "FK_443b0bff9788f060fe1a8ba617b"`);
        await queryRunner.query(`ALTER TABLE "user_story" DROP CONSTRAINT "FK_53ea109ed6a05ae6f9fdc33f794"`);
        await queryRunner.query(`ALTER TABLE "user_story" DROP CONSTRAINT "FK_1b66e59967f8fbf44cb692a8b9a"`);
        await queryRunner.query(`ALTER TABLE "feature" DROP CONSTRAINT "FK_d378ad58975a8693f95bc68c71a"`);
        await queryRunner.query(`ALTER TABLE "feature" DROP CONSTRAINT "FK_313047df0954669919a5b855dde"`);
        await queryRunner.query(`ALTER TABLE "feature" DROP CONSTRAINT "FK_d4a28a8e70d450a412bf0cfb52a"`);
        await queryRunner.query(`ALTER TABLE "feature" DROP CONSTRAINT "FK_0a48658f04433e8a6ccb0a57187"`);
        await queryRunner.query(`ALTER TABLE "feature" DROP CONSTRAINT "FK_dc2864acf0c06997e5dc0f47dbe"`);
        await queryRunner.query(`ALTER TABLE "feature" DROP CONSTRAINT "FK_00c4427a81e82a5ee40b1b40e97"`);
        await queryRunner.query(`ALTER TABLE "Epic" DROP CONSTRAINT "FK_e3a15ca42ced20d50f91bc1b785"`);
        await queryRunner.query(`ALTER TABLE "Epic" DROP CONSTRAINT "FK_2a1adf93f3dbc64246c130a3085"`);
        await queryRunner.query(`ALTER TABLE "Epic" DROP CONSTRAINT "FK_a0ca985e88555e335ea702790fd"`);
        await queryRunner.query(`ALTER TABLE "Epic" DROP CONSTRAINT "FK_245575a06243d764b5dafb6a3b4"`);
        await queryRunner.query(`ALTER TABLE "Epic" DROP CONSTRAINT "FK_ef76326f3b3a9431f920615af7e"`);
        await queryRunner.query(`ALTER TABLE "Epic" DROP CONSTRAINT "FK_5c6d1d8cd86a91c25aff7b33bf1"`);
        await queryRunner.query(`ALTER TABLE "workitem" DROP CONSTRAINT "FK_f0947da6fb5b37de0826cf7d148"`);
        await queryRunner.query(`ALTER TABLE "workitem" DROP CONSTRAINT "FK_91b83126018679cac7433168cfb"`);
        await queryRunner.query(`ALTER TABLE "workitem" DROP CONSTRAINT "FK_82668fcf730240dc924f9b7e68c"`);
        await queryRunner.query(`ALTER TABLE "workitem" DROP CONSTRAINT "FK_ed18c8b38a8921df0008cc4577f"`);
        await queryRunner.query(`ALTER TABLE "workitem" DROP CONSTRAINT "FK_fb11a5d6971c2a341aa1f3f3943"`);
        await queryRunner.query(`ALTER TABLE "workitem" DROP CONSTRAINT "FK_6ac10d55b031facc4808deda253"`);
        await queryRunner.query(`ALTER TABLE "discussion" DROP CONSTRAINT "FK_619cb0165968ce3632e71f929d8"`);
        await queryRunner.query(`ALTER TABLE "discussion" DROP CONSTRAINT "FK_6a5c08cba60dde8720f8e86da9d"`);
        await queryRunner.query(`ALTER TABLE "project_member" DROP CONSTRAINT "FK_aaef76230abfcdf30adb15d0be8"`);
        await queryRunner.query(`ALTER TABLE "project_member" DROP CONSTRAINT "FK_c5aa3e0aec43d3459e159d21dd3"`);
        await queryRunner.query(`ALTER TABLE "project" DROP CONSTRAINT "FK_6b512aa40369ca997e833f568ce"`);
        await queryRunner.query(`ALTER TABLE "sprint" DROP CONSTRAINT "FK_d43446a72eb18ee4cd06a8a510d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e94e9a75d10fdc7e34fb8deb61"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df9eb6d28d3088641e8992776d"`);
        await queryRunner.query(`DROP TABLE "user_story_tags_tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_716bcb0af33e71263af530e1fd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c11c3d7ebca48ade507892449d"`);
        await queryRunner.query(`DROP TABLE "feature_tags_tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2aa188f4d155734448d318f3ab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c76d2381e0d70dd020c58fec8"`);
        await queryRunner.query(`DROP TABLE "epic_tags_tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d0171023239e6acba6c3aa4a8e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bfae51d139fe3ffd6d3936eb26"`);
        await queryRunner.query(`DROP TABLE "workitem_tags_tags"`);
        await queryRunner.query(`DROP TABLE "user_story"`);
        await queryRunner.query(`DROP TYPE "public"."user_story_state_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_story_type_enum"`);
        await queryRunner.query(`DROP TABLE "feature"`);
        await queryRunner.query(`DROP TYPE "public"."feature_state_enum"`);
        await queryRunner.query(`DROP TYPE "public"."feature_type_enum"`);
        await queryRunner.query(`DROP TABLE "Epic"`);
        await queryRunner.query(`DROP TYPE "public"."Epic_state_enum"`);
        await queryRunner.query(`DROP TYPE "public"."Epic_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_95ec63252523517b0b499e2a3f"`);
        await queryRunner.query(`DROP TABLE "workitem"`);
        await queryRunner.query(`DROP TYPE "public"."workitem_state_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workitem_type_enum"`);
        await queryRunner.query(`DROP TABLE "planning"`);
        await queryRunner.query(`DROP TYPE "public"."planning_risk_enum"`);
        await queryRunner.query(`DROP TABLE "tags"`);
        await queryRunner.query(`DROP TABLE "discussion"`);
        await queryRunner.query(`DROP TABLE "User"`);
        await queryRunner.query(`DROP TABLE "project_member"`);
        await queryRunner.query(`DROP TABLE "project"`);
        await queryRunner.query(`DROP TABLE "sprint"`);
    }

}
